version: '3.1'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PORT: 5000
    ports:
      - "5000:80"
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flashcards_db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
