"""Fixed bug

Revision ID: 7245a36368e7
Revises: 453cfcf23d28
Create Date: 2023-02-23 17:38:24.419378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7245a36368e7'
down_revision = '453cfcf23d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_set_categories', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_set_categories', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###
