"""empty message

Revision ID: 866578d8d1df
Revises: 
Create Date: 2023-02-23 07:47:11.249545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866578d8d1df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('card_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_set_saves',
    sa.Column('cardset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cardset_id'], ['card_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cardset_id', 'user_id')
    )
    op.create_table('flash_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('content', sa.String(length=300), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('cardset_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cardset_id'], ['card_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('card_audio')
    op.drop_table('card_set')
    op.drop_table('card_image')
    op.drop_table('flash_card')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('username', name='user_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('card_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('side', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['flash_card.id'], name='card_image_card_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='card_image_pkey')
    )
    op.create_table('flash_card',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('flash_card_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='flash_card_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='flash_card_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('card_set',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='card_set_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='card_set_pkey')
    )
    op.create_table('card_audio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('audio', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('side', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['flash_card.id'], name='card_audio_card_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='card_audio_pkey')
    )
    op.drop_table('flash_cards')
    op.drop_table('card_set_saves')
    op.drop_table('card_sets')
    op.drop_table('users')
    # ### end Alembic commands ###
